# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    trusted_proxies: '127.0.0.1'
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_samesite: none
        cookie_secure: auto
        # Keep the session cookie for 1 day (86400 seconds)
        cookie_lifetime: 86400

        # Keep the session file on the server for 1 day
        gc_maxlifetime: 86400

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
