<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260519115130 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cycle_assignment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, week_number INT NOT NULL, day_of_week INT NOT NULL, cycle_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_601168825EC1162 ON cycle_assignment (cycle_id)');
        $this->addSql('CREATE INDEX IDX_6011688212469DE2 ON cycle_assignment (category_id)');
        $this->addSql('CREATE TABLE training_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color_hex VARCHAR(7) NOT NULL, company_id INT NOT NULL, trainer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E1290A56979B1AD6 ON training_category (company_id)');
        $this->addSql('CREATE INDEX IDX_E1290A56FB08EDF6 ON training_category (trainer_id)');
        $this->addSql('CREATE TABLE training_cycle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, start_date DATE NOT NULL, duration_weeks INT NOT NULL, is_active BOOLEAN NOT NULL, company_id INT NOT NULL, trainer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5F5C5BFE979B1AD6 ON training_cycle (company_id)');
        $this->addSql('CREATE INDEX IDX_5F5C5BFEFB08EDF6 ON training_cycle (trainer_id)');
        $this->addSql('ALTER TABLE cycle_assignment ADD CONSTRAINT FK_601168825EC1162 FOREIGN KEY (cycle_id) REFERENCES training_cycle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cycle_assignment ADD CONSTRAINT FK_6011688212469DE2 FOREIGN KEY (category_id) REFERENCES training_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_category ADD CONSTRAINT FK_E1290A56979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_category ADD CONSTRAINT FK_E1290A56FB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_cycle ADD CONSTRAINT FK_5F5C5BFE979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_cycle ADD CONSTRAINT FK_5F5C5BFEFB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cycle_assignment DROP CONSTRAINT FK_601168825EC1162');
        $this->addSql('ALTER TABLE cycle_assignment DROP CONSTRAINT FK_6011688212469DE2');
        $this->addSql('ALTER TABLE training_category DROP CONSTRAINT FK_E1290A56979B1AD6');
        $this->addSql('ALTER TABLE training_category DROP CONSTRAINT FK_E1290A56FB08EDF6');
        $this->addSql('ALTER TABLE training_cycle DROP CONSTRAINT FK_5F5C5BFE979B1AD6');
        $this->addSql('ALTER TABLE training_cycle DROP CONSTRAINT FK_5F5C5BFEFB08EDF6');
        $this->addSql('DROP TABLE cycle_assignment');
        $this->addSql('DROP TABLE training_category');
        $this->addSql('DROP TABLE training_cycle');
    }
}
