<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604126050 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stripe_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stripe_account_id VARCHAR(255) DEFAULT NULL, stripe_product_setup_fee_id VARCHAR(255) DEFAULT NULL, stripe_product_membership_id VARCHAR(255) DEFAULT NULL, stripe_onboarding_complete BOOLEAN DEFAULT NULL, stripe_price_setup_fee_id VARCHAR(255) DEFAULT NULL, stripe_price_yearly_recurring_id VARCHAR(255) DEFAULT NULL, stripe_price_membership_id VARCHAR(255) DEFAULT NULL, billing_cycle_anchor_day INT DEFAULT NULL, yearly_fee_enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE company ADD stripe_config_id INT DEFAULT NULL');

        // Data migration: Move existing data from company to stripe_config
        $this->addSql('INSERT INTO stripe_config (stripe_account_id, stripe_onboarding_complete, stripe_price_setup_fee_id, stripe_price_membership_id, billing_cycle_anchor_day, yearly_fee_enabled, stripe_price_yearly_recurring_id, stripe_product_setup_fee_id, stripe_product_membership_id)
                       SELECT stripe_account_id, stripe_onboarding_complete, stripe_price_setup_fee_id, stripe_price_membership_id, billing_cycle_anchor_day, yearly_fee_enabled, stripe_price_yearly_recurring_id, stripe_product_setup_fee_id, stripe_product_membership_id FROM company');

        $this->addSql('UPDATE company SET stripe_config_id = (SELECT id FROM stripe_config sc WHERE sc.stripe_account_id = company.stripe_account_id OR (sc.stripe_account_id IS NULL AND company.stripe_account_id IS NULL) LIMIT 1)');

        // Make stripe_config_id NOT NULL after data migration
        $this->addSql('ALTER TABLE company ALTER COLUMN stripe_config_id SET NOT NULL');

        $this->addSql('ALTER TABLE company DROP stripe_account_id');
        $this->addSql('ALTER TABLE company DROP stripe_onboarding_complete');
        $this->addSql('ALTER TABLE company DROP stripe_price_setup_fee_id');
        $this->addSql('ALTER TABLE company DROP stripe_price_membership_id');
        $this->addSql('ALTER TABLE company DROP billing_cycle_anchor_day');
        $this->addSql('ALTER TABLE company DROP yearly_fee_enabled');
        $this->addSql('ALTER TABLE company DROP stripe_price_yearly_recurring_id');
        $this->addSql('ALTER TABLE company DROP stripe_product_setup_fee_id');
        $this->addSql('ALTER TABLE company DROP stripe_product_membership_id');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F9B562049 FOREIGN KEY (stripe_config_id) REFERENCES stripe_config (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094F9B562049 ON company (stripe_config_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE stripe_config');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094F9B562049');
        $this->addSql('DROP INDEX UNIQ_4FBF094F9B562049');
        $this->addSql('ALTER TABLE company ADD stripe_account_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_onboarding_complete BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_price_setup_fee_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_price_membership_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD billing_cycle_anchor_day INT DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD yearly_fee_enabled BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_price_yearly_recurring_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_product_setup_fee_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_product_membership_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company DROP stripe_config_id');
    }
}
