<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260530211425 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meetup_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, meetup_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_629734E0979B1AD6 ON meetup_comment (company_id)');
        $this->addSql('CREATE INDEX IDX_629734E0591E2316 ON meetup_comment (meetup_id)');
        $this->addSql('CREATE INDEX IDX_629734E0F675F31B ON meetup_comment (author_id)');
        $this->addSql('CREATE TABLE meetup_user_read_state (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, user_id INT NOT NULL, meetup_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E0224D58979B1AD6 ON meetup_user_read_state (company_id)');
        $this->addSql('CREATE INDEX IDX_E0224D58A76ED395 ON meetup_user_read_state (user_id)');
        $this->addSql('CREATE INDEX IDX_E0224D58591E2316 ON meetup_user_read_state (meetup_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MEETUP_USER_READ ON meetup_user_read_state (user_id, meetup_id)');
        $this->addSql('ALTER TABLE meetup_comment ADD CONSTRAINT FK_629734E0979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup_comment ADD CONSTRAINT FK_629734E0591E2316 FOREIGN KEY (meetup_id) REFERENCES meetup (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup_comment ADD CONSTRAINT FK_629734E0F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup_user_read_state ADD CONSTRAINT FK_E0224D58979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup_user_read_state ADD CONSTRAINT FK_E0224D58A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup_user_read_state ADD CONSTRAINT FK_E0224D58591E2316 FOREIGN KEY (meetup_id) REFERENCES meetup (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup ALTER meetup_date DROP NOT NULL');
        $this->addSql('ALTER TABLE meetup ALTER rsvp_deadline DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE meetup_comment DROP CONSTRAINT FK_629734E0979B1AD6');
        $this->addSql('ALTER TABLE meetup_comment DROP CONSTRAINT FK_629734E0591E2316');
        $this->addSql('ALTER TABLE meetup_comment DROP CONSTRAINT FK_629734E0F675F31B');
        $this->addSql('ALTER TABLE meetup_user_read_state DROP CONSTRAINT FK_E0224D58979B1AD6');
        $this->addSql('ALTER TABLE meetup_user_read_state DROP CONSTRAINT FK_E0224D58A76ED395');
        $this->addSql('ALTER TABLE meetup_user_read_state DROP CONSTRAINT FK_E0224D58591E2316');
        $this->addSql('DROP TABLE meetup_comment');
        $this->addSql('DROP TABLE meetup_user_read_state');
        $this->addSql('ALTER TABLE meetup ALTER meetup_date SET NOT NULL');
        $this->addSql('ALTER TABLE meetup ALTER rsvp_deadline SET NOT NULL');
    }
}
