<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429104440 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE legal_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, legal_notice_company_name VARCHAR(255) DEFAULT NULL, legal_notice_representative VARCHAR(255) DEFAULT NULL, legal_notice_street VARCHAR(255) DEFAULT NULL, legal_notice_house_number VARCHAR(20) DEFAULT NULL, legal_notice_zip_code VARCHAR(20) DEFAULT NULL, legal_notice_city VARCHAR(255) DEFAULT NULL, legal_notice_email VARCHAR(255) DEFAULT NULL, legal_notice_phone VARCHAR(255) DEFAULT NULL, legal_notice_tax_id VARCHAR(255) DEFAULT NULL, legal_notice_vat_id VARCHAR(255) DEFAULT NULL, privacy_policy_pdf_path VARCHAR(255) DEFAULT NULL, legal_notice_markdown TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_company_name');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_representative');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_email');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_phone');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_tax_id');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_vat_id');
        $this->addSql('ALTER TABLE global_settings DROP privacy_policy_pdf_path');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_street');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_house_number');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_zip_code');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_city');
        $this->addSql('ALTER TABLE global_settings DROP legal_notice_markdown');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE legal_settings');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_company_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_representative VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_email VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_phone VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_tax_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_vat_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD privacy_policy_pdf_path VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_street VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_house_number VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_zip_code VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_city VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE global_settings ADD legal_notice_markdown TEXT DEFAULT NULL');
    }
}
