<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260501074702 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, admin_settings_id INT DEFAULT NULL, global_settings_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094F5E237E06 ON company (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094FC48ED181 ON company (admin_settings_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094F2377CD0A ON company (global_settings_id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FC48ED181 FOREIGN KEY (admin_settings_id) REFERENCES admin_settings (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F2377CD0A FOREIGN KEY (global_settings_id) REFERENCES global_settings (id)');
        $this->addSql('ALTER TABLE "user" ADD company_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8D93D649979B1AD6 ON "user" (company_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094FC48ED181');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094F2377CD0A');
        $this->addSql('DROP TABLE company');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE979B1AD6');
        $this->addSql('DROP INDEX IDX_E00CEDDE979B1AD6');
        $this->addSql('ALTER TABLE booking DROP company_id');
        $this->addSql('ALTER TABLE course DROP CONSTRAINT FK_169E6FB9979B1AD6');
        $this->addSql('DROP INDEX IDX_169E6FB9979B1AD6');
        $this->addSql('ALTER TABLE course DROP company_id');
        $this->addSql('ALTER TABLE course_series DROP CONSTRAINT FK_9428C060979B1AD6');
        $this->addSql('DROP INDEX IDX_9428C060979B1AD6');
        $this->addSql('ALTER TABLE course_series DROP company_id');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA979B1AD6');
        $this->addSql('DROP INDEX IDX_BF5476CA979B1AD6');
        $this->addSql('ALTER TABLE notification DROP company_id');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649979B1AD6');
        $this->addSql('DROP INDEX IDX_8D93D649979B1AD6');
        $this->addSql('ALTER TABLE "user" DROP company_id');
    }
}
