<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604125003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add smtp_settings table and link it to company.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE smtp_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, host VARCHAR(255) DEFAULT NULL, port INT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, encryption VARCHAR(20) DEFAULT NULL, use_custom_smtp BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE company ADD smtp_settings_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F91EED792 FOREIGN KEY (smtp_settings_id) REFERENCES smtp_settings (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094F91EED792 ON company (smtp_settings_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094F91EED792');
        $this->addSql('DROP INDEX UNIQ_4FBF094F91EED792');
        $this->addSql('ALTER TABLE company DROP COLUMN smtp_settings_id');
        $this->addSql('DROP TABLE smtp_settings');
    }
}
