<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520132135 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_workout_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exercise_name VARCHAR(255) NOT NULL, weight_value DOUBLE PRECISION NOT NULL, date_achieved TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA325F06A76ED395 ON user_workout_record (user_id)');
        $this->addSql('ALTER TABLE user_workout_record ADD CONSTRAINT FK_EA325F06A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_workout_record DROP CONSTRAINT FK_EA325F06A76ED395');
        $this->addSql('DROP TABLE user_workout_record');
    }
}
