<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260604126120 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // 1. Create the table and add the column
        $this->addSql('CREATE TABLE stripe_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, stripe_account_id VARCHAR(255) DEFAULT NULL, stripe_product_setup_fee_id VARCHAR(255) DEFAULT NULL, stripe_product_membership_id VARCHAR(255) DEFAULT NULL, stripe_onboarding_complete BOOLEAN DEFAULT NULL, stripe_price_setup_fee_id VARCHAR(255) DEFAULT NULL, stripe_price_yearly_recurring_id VARCHAR(255) DEFAULT NULL, stripe_price_membership_id VARCHAR(255) DEFAULT NULL, billing_cycle_anchor_day INT DEFAULT NULL, yearly_fee_enabled BOOLEAN DEFAULT true NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE company ADD stripe_config_id INT DEFAULT NULL');

        // --- DATA MIGRATION FIX ---
        // 2. Add a temporary column to map the records exactly 1-to-1
        $this->addSql('ALTER TABLE stripe_config ADD tmp_company_id INT DEFAULT NULL');

        // 3. Insert the data, pulling over the company.id into our temporary column
        $this->addSql('INSERT INTO stripe_config (tmp_company_id, stripe_account_id, stripe_onboarding_complete, stripe_price_setup_fee_id, stripe_price_membership_id, billing_cycle_anchor_day, yearly_fee_enabled, stripe_price_yearly_recurring_id, stripe_product_setup_fee_id, stripe_product_membership_id)
                       SELECT id, stripe_account_id, stripe_onboarding_complete, stripe_price_setup_fee_id, stripe_price_membership_id, billing_cycle_anchor_day, yearly_fee_enabled, stripe_price_yearly_recurring_id, stripe_product_setup_fee_id, stripe_product_membership_id FROM company');

        // 4. Update the company table using the exact mapping
        $this->addSql('UPDATE company SET stripe_config_id = stripe_config.id FROM stripe_config WHERE stripe_config.tmp_company_id = company.id');

        // 5. Drop the temporary column as it is no longer needed
        $this->addSql('ALTER TABLE stripe_config DROP tmp_company_id');
        // --------------------------

        // 6. Enforce NOT NULL, drop old columns, and add constraints
        $this->addSql('ALTER TABLE company ALTER COLUMN stripe_config_id SET NOT NULL');

        $this->addSql('ALTER TABLE company DROP stripe_account_id');
        $this->addSql('ALTER TABLE company DROP stripe_onboarding_complete');
        $this->addSql('ALTER TABLE company DROP stripe_price_setup_fee_id');
        $this->addSql('ALTER TABLE company DROP stripe_price_membership_id');
        $this->addSql('ALTER TABLE company DROP billing_cycle_anchor_day');
        $this->addSql('ALTER TABLE company DROP yearly_fee_enabled');
        $this->addSql('ALTER TABLE company DROP stripe_price_yearly_recurring_id');
        $this->addSql('ALTER TABLE company DROP stripe_product_setup_fee_id');
        $this->addSql('ALTER TABLE company DROP stripe_product_membership_id');

        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F9B562049 FOREIGN KEY (stripe_config_id) REFERENCES stripe_config (id) NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FBF094F9B562049 ON company (stripe_config_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE stripe_config');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094F9B562049');
        $this->addSql('DROP INDEX UNIQ_4FBF094F9B562049');
        $this->addSql('ALTER TABLE company ADD stripe_account_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_onboarding_complete BOOLEAN DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_price_setup_fee_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_price_membership_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD billing_cycle_anchor_day INT DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD yearly_fee_enabled BOOLEAN DEFAULT true NOT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_price_yearly_recurring_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_product_setup_fee_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company ADD stripe_product_membership_id VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE company DROP stripe_config_id');
    }
}
