<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260518201923 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sensitive_data_access_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, accessed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reason VARCHAR(255) NOT NULL, viewer_id INT NOT NULL, target_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B89A2AF6C59C752 ON sensitive_data_access_log (viewer_id)');
        $this->addSql('CREATE INDEX IDX_9B89A2AF6C066AFE ON sensitive_data_access_log (target_user_id)');
        $this->addSql('ALTER TABLE sensitive_data_access_log ADD CONSTRAINT FK_9B89A2AF6C59C752 FOREIGN KEY (viewer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sensitive_data_access_log ADD CONSTRAINT FK_9B89A2AF6C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD phone_number VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD emergency_contact_name VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD emergency_contact_phone VARCHAR(20) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sensitive_data_access_log DROP CONSTRAINT FK_9B89A2AF6C59C752');
        $this->addSql('ALTER TABLE sensitive_data_access_log DROP CONSTRAINT FK_9B89A2AF6C066AFE');
        $this->addSql('DROP TABLE sensitive_data_access_log');
        $this->addSql('ALTER TABLE "user" DROP phone_number');
        $this->addSql('ALTER TABLE "user" DROP emergency_contact_name');
        $this->addSql('ALTER TABLE "user" DROP emergency_contact_phone');
    }
}
