<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260520150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create exercise table and populate with CrossFit exercises';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(50) NOT NULL, unit VARCHAR(20) DEFAULT \'kg\' NOT NULL, PRIMARY KEY(id))');
        
        $exercises = [
            // Weightlifting
            ['Back Squat', 'Weightlifting', 'kg'],
            ['Front Squat', 'Weightlifting', 'kg'],
            ['Overhead Squat', 'Weightlifting', 'kg'],
            ['Deadlift', 'Weightlifting', 'kg'],
            ['Sumo Deadlift High Pull', 'Weightlifting', 'kg'],
            ['Shoulder Press', 'Weightlifting', 'kg'],
            ['Push Press', 'Weightlifting', 'kg'],
            ['Push Jerk', 'Weightlifting', 'kg'],
            ['Bench Press', 'Weightlifting', 'kg'],
            ['Snatch', 'Weightlifting', 'kg'],
            ['Power Snatch', 'Weightlifting', 'kg'],
            ['Squat Snatch', 'Weightlifting', 'kg'],
            ['Clean & Jerk', 'Weightlifting', 'kg'],
            ['Clean', 'Weightlifting', 'kg'],
            ['Power Clean', 'Weightlifting', 'kg'],
            ['Squat Clean', 'Weightlifting', 'kg'],
            ['Thruster', 'Weightlifting', 'kg'],
            ['Wall Ball', 'Weightlifting', 'kg'],
            ['Kettlebell Swing', 'Weightlifting', 'kg'],
            ['Dumbbell Snatch', 'Weightlifting', 'kg'],
            ['Goblet Squat', 'Weightlifting', 'kg'],
            ['Farmer\'s Carry', 'Weightlifting', 'kg'],
            ['Sandbag Clean', 'Weightlifting', 'kg'],
            
            // Gymnastics
            ['Pull-up', 'Gymnastics', 'reps'],
            ['Chest-to-Bar', 'Gymnastics', 'reps'],
            ['Muscle-up (Bar)', 'Gymnastics', 'reps'],
            ['Muscle-up (Ring)', 'Gymnastics', 'reps'],
            ['Handstand Push-up', 'Gymnastics', 'reps'],
            ['Dip', 'Gymnastics', 'reps'],
            ['Ring Dip', 'Gymnastics', 'reps'],
            ['Toes-to-Bar', 'Gymnastics', 'reps'],
            ['Knees-to-Elbows', 'Gymnastics', 'reps'],
            ['Sit-up', 'Gymnastics', 'reps'],
            ['GHD Sit-up', 'Gymnastics', 'reps'],
            ['Burpee', 'Gymnastics', 'reps'],
            ['Air Squat', 'Gymnastics', 'reps'],
            ['Push-up', 'Gymnastics', 'reps'],
            ['L-sit', 'Gymnastics', 'sec'],
            ['Handstand Walk', 'Gymnastics', 'm'],
            ['Rope Climb', 'Gymnastics', 'reps'],
            ['Pistol Squat', 'Gymnastics', 'reps'],
            ['Wall Walk', 'Gymnastics', 'reps'],
            
            // Monostructural
            ['Run (400m)', 'Monostructural', 'time'],
            ['Run (800m)', 'Monostructural', 'time'],
            ['Run (1600m)', 'Monostructural', 'time'],
            ['Row (500m)', 'Monostructural', 'time'],
            ['Row (1000m)', 'Monostructural', 'time'],
            ['Row (2000m)', 'Monostructural', 'time'],
            ['BikeErg (1000m)', 'Monostructural', 'time'],
            ['Assault Bike (Calories)', 'Monostructural', 'cal'],
            ['SkiErg (500m)', 'Monostructural', 'time'],
            ['Double Under', 'Monostructural', 'reps'],
            ['Box Jump', 'Monostructural', 'reps'],
            ['Box Step-up', 'Monostructural', 'reps'],
        ];

        foreach ($exercises as $ex) {
            $this->addSql('INSERT INTO exercise (name, category, unit) VALUES (?, ?, ?)', $ex);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE exercise');
    }
}
