<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611115357 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE platform_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operator_name VARCHAR(255) DEFAULT NULL, operator_company VARCHAR(255) DEFAULT NULL, operator_details TEXT DEFAULT NULL, operator_street VARCHAR(255) DEFAULT NULL, operator_house_number VARCHAR(20) DEFAULT NULL, operator_zip_code VARCHAR(20) DEFAULT NULL, operator_city VARCHAR(255) DEFAULT NULL, operator_email VARCHAR(255) DEFAULT NULL, operator_phone VARCHAR(255) DEFAULT NULL, profession VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, tax_id VARCHAR(255) DEFAULT NULL, vat_id VARCHAR(255) DEFAULT NULL, privacy_policy_pdf_path VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE platform_settings');
    }
}
