<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260501074418 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admin_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, company_name VARCHAR(255) NOT NULL, legal_notice_representative VARCHAR(255) DEFAULT NULL, legal_notice_street VARCHAR(255) DEFAULT NULL, legal_notice_house_number VARCHAR(20) DEFAULT NULL, legal_notice_zip_code VARCHAR(20) DEFAULT NULL, legal_notice_city VARCHAR(255) DEFAULT NULL, legal_notice_email VARCHAR(255) DEFAULT NULL, legal_notice_phone VARCHAR(255) DEFAULT NULL, legal_notice_tax_id VARCHAR(255) DEFAULT NULL, legal_notice_vat_id VARCHAR(255) DEFAULT NULL, privacy_policy_pdf_path VARCHAR(255) DEFAULT NULL, legal_notice_markdown TEXT DEFAULT NULL, terms_and_conditions_markdown TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_71E5A7C31D4E64E8 ON admin_settings (company_name)');
        $this->addSql('DROP TABLE legal_settings');
        $this->addSql('DROP INDEX uniq_3223f6eb65b9c3ff');
        $this->addSql('ALTER TABLE global_settings DROP site_name');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE legal_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, legal_notice_company_name VARCHAR(255) DEFAULT NULL, legal_notice_representative VARCHAR(255) DEFAULT NULL, legal_notice_street VARCHAR(255) DEFAULT NULL, legal_notice_house_number VARCHAR(20) DEFAULT NULL, legal_notice_zip_code VARCHAR(20) DEFAULT NULL, legal_notice_city VARCHAR(255) DEFAULT NULL, legal_notice_email VARCHAR(255) DEFAULT NULL, legal_notice_phone VARCHAR(255) DEFAULT NULL, legal_notice_tax_id VARCHAR(255) DEFAULT NULL, legal_notice_vat_id VARCHAR(255) DEFAULT NULL, privacy_policy_pdf_path VARCHAR(255) DEFAULT NULL, legal_notice_markdown TEXT DEFAULT NULL, terms_and_conditions_markdown TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE admin_settings');
        $this->addSql('ALTER TABLE global_settings ADD site_name VARCHAR(255) DEFAULT \'Phoenix Athletics\' NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX uniq_3223f6eb65b9c3ff ON global_settings (site_name)');
    }
}
