<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511195752 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE meetup (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, meetup_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, location VARCHAR(255) NOT NULL, image_url VARCHAR(255) DEFAULT NULL, min_participants INT DEFAULT NULL, max_participants INT DEFAULT NULL, rsvp_deadline TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9377E28979B1AD6 ON meetup (company_id)');
        $this->addSql('CREATE INDEX IDX_9377E2861220EA6 ON meetup (creator_id)');
        $this->addSql('CREATE TABLE meetup_rsvp (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, meetup_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_48374563979B1AD6 ON meetup_rsvp (company_id)');
        $this->addSql('CREATE INDEX IDX_48374563591E2316 ON meetup_rsvp (meetup_id)');
        $this->addSql('CREATE INDEX IDX_48374563A76ED395 ON meetup_rsvp (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MEETUP_USER ON meetup_rsvp (meetup_id, user_id)');
        $this->addSql('ALTER TABLE meetup ADD CONSTRAINT FK_9377E28979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup ADD CONSTRAINT FK_9377E2861220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup_rsvp ADD CONSTRAINT FK_48374563979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup_rsvp ADD CONSTRAINT FK_48374563591E2316 FOREIGN KEY (meetup_id) REFERENCES meetup (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE meetup_rsvp ADD CONSTRAINT FK_48374563A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE meetup DROP CONSTRAINT FK_9377E28979B1AD6');
        $this->addSql('ALTER TABLE meetup DROP CONSTRAINT FK_9377E2861220EA6');
        $this->addSql('ALTER TABLE meetup_rsvp DROP CONSTRAINT FK_48374563979B1AD6');
        $this->addSql('ALTER TABLE meetup_rsvp DROP CONSTRAINT FK_48374563591E2316');
        $this->addSql('ALTER TABLE meetup_rsvp DROP CONSTRAINT FK_48374563A76ED395');
        $this->addSql('DROP TABLE meetup');
        $this->addSql('DROP TABLE meetup_rsvp');
    }
}
