<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260424134638 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trainer_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, show_participant_names BOOLEAN DEFAULT true NOT NULL, show_waitlist_names BOOLEAN DEFAULT true NOT NULL, is_waitlist_visible BOOLEAN DEFAULT true NOT NULL, trainer_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EE5240DDFB08EDF6 ON trainer_settings (trainer_id)');
        $this->addSql('ALTER TABLE trainer_settings ADD CONSTRAINT FK_EE5240DDFB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" DROP show_participant_names');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trainer_settings DROP CONSTRAINT FK_EE5240DDFB08EDF6');
        $this->addSql('DROP TABLE trainer_settings');
        $this->addSql('ALTER TABLE "user" ADD show_participant_names BOOLEAN DEFAULT true NOT NULL');
    }
}
