<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260428114112 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create CourseSeries table and migrate existing series_id to the new structure.';
    }

    public function up(Schema $schema): void
    {
        // 1. Create course_series table
        $this->addSql('CREATE TABLE course_series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, trainer_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, capacity INT NOT NULL, schedule_start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_minutes INT NOT NULL, frequency VARCHAR(255) NOT NULL, last_generated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9428C060FB08EDF6 ON course_series (trainer_id)');
        $this->addSql('ALTER TABLE course_series ADD CONSTRAINT FK_9428C060FB08EDF6 FOREIGN KEY (trainer_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // 2. Add temporary series_rel_id to course
        $this->addSql('ALTER TABLE course ADD series_rel_id INT DEFAULT NULL');

        // 3. Migrate data from old series_id to new course_series table
        // We group courses by series_id and create a series record for each unique series_id
        $this->addSql('
            INSERT INTO course_series (trainer_id, title, description, capacity, schedule_start_time, duration_minutes, frequency, created_at, active, last_generated_date)
            SELECT DISTINCT ON (series_id) 
                trainer_id, title, description, capacity, start_time, duration_minutes, frequency, NOW(), TRUE, (SELECT MAX(start_time) FROM course c2 WHERE c2.series_id = c.series_id)
            FROM course c
            WHERE series_id IS NOT NULL
        ');

        // 4. Update course table to point to the new series records
        $this->addSql('
            UPDATE course c
            SET series_rel_id = cs.id
            FROM course_series cs
            WHERE c.series_id = cs.title -- This is slightly risky if titles match but series_ids differ, but let\'s use a better match
        ');
        
        // Re-do 4 with a more reliable match: we need to join on the original series_id
        // Since we didn\'t store the old series_id in course_series, let\'s add it temporarily or use a subquery
        $this->addSql('ALTER TABLE course_series ADD temp_old_id VARCHAR(255)');
        
        $this->addSql('DELETE FROM course_series'); // Start over with temp_old_id
        $this->addSql('
            INSERT INTO course_series (trainer_id, title, description, capacity, schedule_start_time, duration_minutes, frequency, created_at, active, temp_old_id, last_generated_date)
            SELECT DISTINCT ON (series_id) 
                trainer_id, title, description, capacity, start_time, duration_minutes, frequency, NOW(), TRUE, series_id, (SELECT MAX(start_time) FROM course c2 WHERE c2.series_id = c.series_id)
            FROM course c
            WHERE series_id IS NOT NULL
        ');

        $this->addSql('
            UPDATE course c
            SET series_rel_id = cs.id
            FROM course_series cs
            WHERE c.series_id = cs.temp_old_id
        ');

        // 5. Clean up old series_id and rename series_rel_id to series_id
        $this->addSql('ALTER TABLE course DROP series_id');
        $this->addSql('ALTER TABLE course RENAME COLUMN series_rel_id TO series_id');
        $this->addSql('ALTER TABLE course_series DROP temp_old_id');

        // 6. Add foreign key constraint
        $this->addSql('ALTER TABLE course ADD CONSTRAINT FK_169E6FB95278319C FOREIGN KEY (series_id) REFERENCES course_series (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_169E6FB95278319C ON course (series_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE course DROP CONSTRAINT FK_169E6FB95278319C');
        $this->addSql('DROP INDEX IDX_169E6FB95278319C');
        $this->addSql('ALTER TABLE course RENAME COLUMN series_id TO series_rel_id');
        $this->addSql('ALTER TABLE course ADD series_id VARCHAR(255) DEFAULT NULL');
        
        // Try to restore old series_id if possible
        $this->addSql('
            UPDATE course c
            SET series_id = cs.title -- Best effort restoration
            FROM course_series cs
            WHERE c.series_rel_id = cs.id
        ');

        $this->addSql('ALTER TABLE course DROP series_rel_id');
        $this->addSql('DROP TABLE course_series');
    }
}
